services:
  - type: web
    name: shappno-vps-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /ping
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: worker
    name: shappno-vps-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
      - key: OWNER_ID
        value: 7875541866